version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --info
  # Display minimal restore text
  - cmd: dotnet restore ./src/Octokit.Extensions.sln --verbosity m
build_script:
  - cmd: dotnet build ./src/Octokit.Extensions.sln
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\bin\Debug\netstandard2.0'
   name: lib
clone_depth: 1
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: cd "./src/Octokit.Extensions.Tests.Integration"
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: of
